import 'package:freezed_annotation/freezed_annotation.dart';

// W2D3 in-class challenge, Part 1.4 — the two part directives freezed +
// json_serializable each require. Mirrors the pattern established in
// `lib/data/job_dto.dart`. Both files are produced by
// `dart run build_runner build --delete-conflicting-outputs`.
part 'job_application_dto.freezed.dart';
part 'job_application_dto.g.dart';

/// The wire-shape mirror of the proposed CareerHub API
/// `ApplicationResponse` record.
///
/// The backend's [Application] model exposes `ApplicantId`, `JobListingId`,
/// `SubmittedAt`, and `Status`, plus navigation properties for the
/// applicant and the job listing (see
/// `CareerHub.Api/Models/Application.cs`). The paged list-my-applications
/// endpoint is expected to project this into a flat DTO with the two
/// resolved display strings (`JobTitle`, `CompanyName`) denormalised
/// so the client never has to make a second call per row — the same
/// pattern `/jobs` already follows with `JobResponse.FromListing`.
///
/// Deliberately owns NO knowledge of Isar, Riverpod, or the domain
/// [JobApplication] model. It is a data-shape only.
@freezed
sealed class JobApplicationDto with _$JobApplicationDto {
  const factory JobApplicationDto({
    /// Guid → String, verbatim, as with `JobDto.id`.
    required String applicantId,

    /// Guid → String, the listing this application was submitted against.
    required String jobListingId,

    /// Denormalised at the API layer so the client renders a card without
    /// a second HTTP call. Backend key: `jobTitle`.
    required String jobTitle,

    /// Denormalised at the API layer. Backend key: `companyName`.
    required String companyName,

    /// ISO-8601 date-time string. Kept as `String` on the DTO — parsing
    /// to `DateTime` is a modelling decision that belongs on the way
    /// OUT via `JobApplication.fromDto`.
    required String submittedAt,

    /// Serialised via `JsonStringEnumConverter` on the API side, so this
    /// arrives as one of `Submitted`, `UnderReview`, `Interviewing`,
    /// `Offered`, `Hired`, `Rejected`. The DTO holds the raw string;
    /// the domain layer maps it to an `ApplicationStatus` enum value.
    required String status,
  }) = _JobApplicationDto;

  /// Generated by json_serializable in `job_application_dto.g.dart`.
  factory JobApplicationDto.fromJson(Map<String, dynamic> json) =>
      _$JobApplicationDtoFromJson(json);
}
